version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  pact-broker:
    build: .
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
      PACT_BROKER_HIDE_PACTFLOW_MESSAGES: 'true'
    command: dockerize -wait tcp://postgres:5432 /home/start.sh
    volumes:
      - ./lib:/home/lib
      - ./db:/home/db
      - ./config.ru:/home/config.ru
      - ./tasks:/home/tasks
      - ./Rakefile:/home/Rakefile

volumes:
  postgres-volume:
