default: &default
  database: pact_broker
  username: pact_broker
  password: pact_broker
  encoding: utf8

test:
  default:
    adapter: sqlite
    database: tmp/pact_broker_database_test.sqlite3
  postgres:
    <<: *default
    adapter: postgres
  docker_postgres:
    adapter: postgres
    database: postgres
    username: postgres
    password: postgres
    host: localhost
    port: "5433"
  docker_compose_postgres:
    adapter: postgres
    database: postgres
    username: postgres
    password: postgres
    host: postgres
    port: "5432"
  mysql:
    <<: *default
    adapter: mysql2
  docker_compose_mysql:
    <<: *default
    adapter: mysql2
    host: mysql
  docker_mysql:
    <<: *default
    adapter: mysql2
    host: "192.168.0.9"

development:
  default:
    adapter: sqlite
    database: db/pact_broker_database.sqlite3
  postgres:
    <<: *default
    adapter: postgres
  docker_postgres:
    adapter: postgres
    database: postgres
    username: postgres
    password: postgres
    host: localhost
    port: "5432"
  mysql:
    <<: *default
    adapter: mysql2
  docker_mysql:
    <<: *default
    adapter: mysql2
    host: localhost

production:
  default:
    <<: *default
    adapter: postgres